# Worker-only compose file for running the processing worker
version: '3.8'

services:
  email-processor-worker:
    build: .
    command: ["python", "worker.py"]
    environment:
      DATABASE_URL: postgresql://email_user:email_pass@postgres:5432/email_rag
      POLL_INTERVAL: ${POLL_INTERVAL:-30}
      BATCH_SIZE: ${BATCH_SIZE:-50}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - email-rag-network

networks:
  email-rag-network:
    external: true